"""The daily summary.

Assembled from the graph rather than generated by a model. Every line in it is
either something the user wrote or an inference already stored with its confidence
and provenance, so the whole summary is explainable by construction — there is no
second synthesis step to audit.

What this deliberately does not do:

- **No mood score.** Reducing a day to a number invites tracking it, and a number
  the user cannot interrogate is the opposite of explainable.
- **No trend claims.** "You've been low all week" is a pattern claim; patterns are
  Milestone 2, and they need to be stored as nodes with their own provenance rather
  than computed on the fly for a report.
- **No prompts to write more.** The summary reports what a day held, including
  nothing. Optimizing for engagement is explicitly out of scope.

Recurrence is counted, not interpreted: "came up in 3 entries" is a fact about the
graph. What it means is the user's to decide.
"""

from __future__ import annotations

from datetime import UTC, datetime, time, timedelta
from datetime import date as Date
from uuid import UUID
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

import asyncpg

from tlon.domain.inference import TENTATIVE_THRESHOLD
from tlon.graph.schema import NodeKind

#: Kinds that describe things in the world rather than the user's inner state.
#: Only these are worth counting recurrence for — a Thought recurring is a
#: coincidence of phrasing, whereas a Person recurring is a fact about the day.
ENTITY_KINDS = (NodeKind.PERSON, NodeKind.PLACE, NodeKind.ACTIVITY, NodeKind.EVENT)

#: An entity must appear in at least this many of the day's entries to be worth
#: mentioning. Two is the smallest number for which "recurring" means anything.
MIN_RECURRENCE = 2


class UnknownTimezone(ValueError):
    pass


def day_bounds(day: Date, timezone: str) -> tuple[datetime, datetime]:
    """The UTC instants bounding a calendar day in the user's own timezone.

    A day is a local concept. Someone journalling at 11pm in Stockholm has written
    an entry for that day, not the next one, and computing boundaries in UTC would
    file it wrongly for anyone not on UTC.

    Returned in UTC deliberately. Python does *wall-clock* arithmetic between two
    aware datetimes that share a tzinfo, so a local-midnight pair spanning a
    daylight-saving change subtracts to 24 hours even when only 23 elapsed. Fine
    for the database, which normalizes anyway, but the returned value should mean
    one unambiguous instant rather than depend on how the caller uses it.
    """
    try:
        zone = ZoneInfo(timezone)
    except (ZoneInfoNotFoundError, ValueError) as exc:
        raise UnknownTimezone(f"unknown timezone: {timezone}") from exc

    # A day is added to the local date rather than 24 hours to the instant, so a
    # daylight-saving transition yields a 23- or 25-hour day as it should.
    start_local = datetime.combine(day, time.min, tzinfo=zone)
    end_local = datetime.combine(day + timedelta(days=1), time.min, tzinfo=zone)
    return start_local.astimezone(UTC), end_local.astimezone(UTC)


async def daily_summary(
    pool: asyncpg.Pool, user_id: UUID, day: Date, timezone: str = "UTC"
) -> dict:
    start, end = day_bounds(day, timezone)

    observations = await pool.fetch(
        """
        SELECT o.node_id, o.content, o.source, o.captured_at
        FROM observations o
        JOIN graph_nodes n ON n.id = o.node_id
        WHERE o.user_id = $1
          AND n.deleted_at IS NULL
          AND o.captured_at >= $2 AND o.captured_at < $3
        ORDER BY o.captured_at
        """,
        user_id,
        start,
        end,
    )

    if not observations:
        # An empty day is reported as an empty day. No encouragement to write.
        return {
            "date": day.isoformat(),
            "timezone": timezone,
            "entry_count": 0,
            "observations": [],
            "inferred": [],
            "recurring": [],
        }

    observation_ids = [row["node_id"] for row in observations]

    # Everything inferred from the day's entries, with the count of the day's
    # entries each one cites. Joining through node_provenance rather than filtering
    # inferred nodes by their own created_at means a node extracted later still
    # belongs to the day whose entry produced it.
    inferred = await pool.fetch(
        """
        SELECT n.id, n.kind, n.label, n.confidence, n.epistemic_status, n.extractor,
               count(DISTINCT p.observation_id) AS cites
        FROM graph_nodes n
        JOIN node_provenance p ON p.node_id = n.id
        WHERE n.user_id = $1
          AND n.deleted_at IS NULL
          AND n.kind <> 'Observation'
          AND p.observation_id = ANY($2::uuid[])
        GROUP BY n.id, n.kind, n.label, n.confidence, n.epistemic_status, n.extractor
        ORDER BY n.confidence DESC, n.label
        """,
        user_id,
        observation_ids,
    )

    recurring = [
        {
            "kind": row["kind"],
            "label": row["label"],
            # Stated as a count, not as a meaning.
            "entries": row["cites"],
        }
        for row in inferred
        if row["kind"] in ENTITY_KINDS and row["cites"] >= MIN_RECURRENCE
    ]

    return {
        "date": day.isoformat(),
        "timezone": timezone,
        "entry_count": len(observations),
        "first_capture": observations[0]["captured_at"],
        "last_capture": observations[-1]["captured_at"],
        "observations": [
            {
                "id": str(row["node_id"]),
                "content": row["content"],
                "source": row["source"],
                "captured_at": row["captured_at"],
            }
            for row in observations
        ],
        "inferred": [
            {
                "id": str(row["id"]),
                "kind": row["kind"],
                "label": row["label"],
                "confidence": row["confidence"],
                "epistemic_status": row["epistemic_status"],
                "extractor": row["extractor"],
                # The client renders these differently. A hypothesis the model is
                # unsure of must not look like something the user said.
                "tentative": row["confidence"] < TENTATIVE_THRESHOLD,
                "cites_entries": row["cites"],
            }
            for row in inferred
        ],
        "recurring": recurring,
    }
